#!/bin/bash 

ids=$(docker ps -a | grep " Up " | grep -v CONTAINER | awk '{print $1}')

cmd="multitail"
for id in $ids; do
  name=$(docker ps -a | grep $id | awk '{print $2}' | sed 's/\(.*\):.*/\1/')
  cmd=$cmd" -t $name -l 'docker logs --follow=true --tail=all $id'"
done

eval $cmd

